pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out from base-kube folder jenkins file..'
            }
        }
        stage('Build') {
            steps {
                echo 'Building from demo folder jenkins file..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }
}
